#2 Sprint 10
blaackpanter/java-filmorate pull request #8
Opened 2024-02-26 18:51 UTC by blaackpanter

2024-02-26 21:25 UTC, db-exp requested changes

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean addLike(@PathVariable("id") int id, @PathVariable("userId") int userId) throws UserNotFoundException, FilmNotFoundException, WrongFilmDateException {
тут тоже следует throws убрать - исключения кастомные должны быть Runtime Exception

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean deleteLike(@PathVariable("id") int id, @PathVariable("userId") int userId) throws UserNotFoundException, FilmNotFoundException, WrongFilmDateException {
и тут throws

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilms(@PathVariable("id") int id) throws FilmNotFoundException {
и тут

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
можно не писать Autowired - Spring и так понимает, что надо)

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User updateUser(@Valid @RequestBody User user) throws UserNotFoundException {
тут тоже throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public boolean addFriend(@PathVariable("id") int id, @PathVariable("friendId") int friendId) throws UserNotFoundException {
тут тоже throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public boolean deleteFriend(@PathVariable("id") int id, @PathVariable("friendId") int friendId) throws UserNotFoundException {
тут тоже throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<User> getFriends(@PathVariable("id") int id) throws UserNotFoundException {
тут тоже throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Set<User> getCommonFriends(@PathVariable("id") int id, @PathVariable("otherId") int otherId) throws UserNotFoundException {
тут тоже throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getUser(@PathVariable("id") int id) throws UserNotFoundException {
тут тоже throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public interface FilmService {
тут тоже везде throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +public class FilmServiceImpl implements FilmService {
тут тоже везде throws лучше убрать

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/film/WrongFilmDateException.java
> +public class WrongFilmDateException extends Exception {
правильней extends RuntimeException

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +public interface UserService {
тут как и везде - throws под снос

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
ниже тоже throws под снос, пожалуйста

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmNotFoundException.java
> +public class FilmNotFoundException extends Exception {
extends RuntimeException более корректный вариант для "своих" исключений

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
throws под снос)

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +public interface UserStorage {
скажем throws нет

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
extends RuntimeException

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
вырежи throws, пожалуйста)

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        int id = films.size() + 1;
size при большом размере - операция, требующая ресурсов, проще завести int и инкрементить его

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        int id = users.size() + 1;
так же как у фильмов

2024-02-26 21:25 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
throws!

2024-02-27 10:27 UTC, blaackpanter commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean addLike(@PathVariable("id") int id, @PathVariable("userId") int userId) throws UserNotFoundException, FilmNotFoundException, WrongFilmDateException {
Привет! Всё поправила

2024-02-27 19:19 UTC, db-exp approved these changes

2024-02-28 15:42 UTC, merged